### ISSUE TITLE
UnboundLocalError: local variable 'points' referenced before assignment

### ISSUE THREAD

**Issue by gkeeth** [svg2mod/svg2mod#15]
Me again.
Running svg2mod v0.1.4 on the attached svg results in an error:

```
$ svg2mod -i points_error.svg -p 1.0
Parsing SVG...
Found SVG layer: F.Fab
Found SVG layer: F.SilkS
Writing module file: points_error.kicad_mod
Traceback (most recent call last):
  File "/usr/bin/svg2mod", line 33, in <module>
    sys.exit(load_entry_point('svg2mod==0.1.4', 'console_scripts', 'svg2mod')())
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 107, in main
    exported.write()
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 804, in write
    self._write_modules()
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 1364, in _write_modules
    self._write_module( front = True )
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 735, in _write_module
    self._write_items( group.items, layer, not front )
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 652, in _write_items
    self._write_items( item.items, layer, flip )
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 690, in _write_items
    points, layer, fill, stroke, stroke_width
UnboundLocalError: local variable 'points' referenced before assignment
```

I've stripped out everything except the offending shape -- it's what I would call an arc but that may not be technically correct. Path->Object to Path does not fix the error. 
[points_error.zip](https://github.com/svg2mod/svg2mod/files/5432001/points_error.zip)

**Comment by gkeeth** [comment]
Update: Stroke to Path does fix the error, so I have an easy workaround (and this is stated in the readme). 

If it's not trivial to make arcs work, it would be nice if this returned a helpful message instead of the error above. Another suggestion would be to update the readme to say that arcs need to have "Stroke to Path" run on them; "Object to Path" is not enough.

**Comment by Sodium-Hydrogen** [comment]
I've fixed the crash caused by empty paths, but I haven't added support for ARCs yet

**Comment by Sodium-Hydrogen** [comment]
Arc support has been added so everything should be working now.
