### ISSUE TITLE
ValueError: could not convert string to float: '0.193pt' when converting path

### ISSUE THREAD

**Issue by gkeeth** [svg2mod/svg2mod#17]
Hi, me again with today's episode of clueless user creatively breaks script :)

Minimal not-working example attached. I made a path and added an arrowhead end marker. I ran Stroke to Path and then svg2mod and got this:

```
svg2mod -i backpanel.svg -p 0.1
Parsing SVG...
Found SVG layer: F.Fab
Found SVG layer: F.SilkS
Writing module file: backpanel.kicad_mod
Traceback (most recent call last):
  File "/usr/bin/svg2mod", line 33, in <module>
    sys.exit(load_entry_point('svg2mod===0.1.4.1-2-ga9915dd', 'console_scripts', 'svg2mod')())
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 107, in main
    exported.write()
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 809, in write
    self._write_modules()
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 1369, in _write_modules
    self._write_module( front = True )
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 740, in _write_module
    self._write_items( group.items, layer, not front )
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 652, in _write_items
    self._write_items( item.items, layer, flip )
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 652, in _write_items
    self._write_items( item.items, layer, flip )
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 652, in _write_items
    self._write_items( item.items, layer, flip )
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 668, in _write_items
    fill, stroke, stroke_width = self._get_fill_stroke( item )
  File "/usr/lib/python3.8/site-packages/svg2mod/svg2mod.py", line 539, in _get_fill_stroke
    stroke_width = float( value )
ValueError: could not convert string to float: '0.193pt'
```

[backpanel.zip](https://github.com/svg2mod/svg2mod/files/5436273/backpanel.zip)

**Comment by Sodium-Hydrogen** [comment]
I couldn't reproduce this issue, but I made a fix for it anyway.

**Comment by gkeeth** [comment]
Strange that it wasn’t reproducible. But thanks for the quick fix!

**Comment by gkeeth** [comment]
Just confirming, this is fixed for me. Thanks again!
