### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by FakeDazon** [svg2mod/svg2mod#19]
hi! i ran into this error when trying to convert an svg. the file i used is attached.
`svg2mod -i logo.svg -p 1.0`

```
Parsing SVG...
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pinal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\svg2mod.exe\__main__.py", line 7, in <module>
  File "C:\Users\pinal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\svg2mod\svg2mod.py", line 35, in main
    imported = Svg2ModImport(
  File "C:\Users\pinal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\svg2mod\svg2mod.py", line 479, in __init__
    self.svg = svg.parse( file_name, verbose_print )
  File "C:\Users\pinal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\svg2mod\svg\svg\__init__.py", line 6, in parse
    f = svg.Svg(filename, verbose)
  File "C:\Users\pinal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\svg2mod\svg\svg\svg.py", line 215, in __init__
    self.parse(filename)
  File "C:\Users\pinal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\svg2mod\svg\svg\svg.py", line 241, in parse
    self.viewport_scale = round(float(viewBox[2])/width, 6)
ZeroDivisionError: float division by zero
```
[logo.zip](https://github.com/svg2mod/svg2mod/files/5564191/logo.zip)

**Comment by Sodium-Hydrogen** [comment]
This should be fixed in the latest release `v0.1.4.2` that I just pushed out. Apparently svgs do not need a height or width property flag and that caused svg2mod to crash. I have fixed that so your svg should work again.
