### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Shofuuu** [svg2mod/svg2mod#40]
Any advice, how to fix this?

```
Parsing SVG...
Traceback (most recent call last):
  File "/usr/local/bin/svg2mod", line 11, in <module>
    load_entry_point('svg2mod==0.dev0', 'console_scripts', 'svg2mod')()
  File "/usr/local/lib/python3.8/dist-packages/svg2mod-0.dev0-py3.8.egg/svg2mod/svg2mod.py", line 102, in main
    imported = Svg2ModImport(
  File "/usr/local/lib/python3.8/dist-packages/svg2mod-0.dev0-py3.8.egg/svg2mod/svg2mod.py", line 650, in __init__
    self.svg = svg.parse( file_name)
  File "/usr/local/lib/python3.8/dist-packages/svg2mod-0.dev0-py3.8.egg/svg2mod/svg/__init__.py", line 11, in parse
    return Svg(filename)
  File "/usr/local/lib/python3.8/dist-packages/svg2mod-0.dev0-py3.8.egg/svg2mod/svg/svg.py", line 227, in __init__
    self.parse(filename)
  File "/usr/local/lib/python3.8/dist-packages/svg2mod-0.dev0-py3.8.egg/svg2mod/svg/svg.py", line 272, in parse
    top_group.append(self.root)
  File "/usr/local/lib/python3.8/dist-packages/svg2mod-0.dev0-py3.8.egg/svg2mod/svg/svg.py", line 346, in append
    item.append(elt)
  File "/usr/local/lib/python3.8/dist-packages/svg2mod-0.dev0-py3.8.egg/svg2mod/svg/svg.py", line 335, in append
    item = elt_class(elt)
  File "/usr/local/lib/python3.8/dist-packages/svg2mod-0.dev0-py3.8.egg/svg2mod/svg/svg.py", line 1033, in __init__
    self.parse(elt, parent)
  File "/usr/local/lib/python3.8/dist-packages/svg2mod-0.dev0-py3.8.egg/svg2mod/svg/svg.py", line 1110, in parse
    value = nv[ 1 ].strip()
IndexError: list index out of range
```

**Comment by Sodium-Hydrogen** [comment]
Can you provide a sample svg and the command that caused this error to occur?

**Comment by Albert-IV** [comment]
I know Shofuuu didn't respond, but here is an example SVG that triggers the same error message.  It isn't the most simple example, but it may give you something to look at.

[example-svg.tar.gz](https://github.com/svg2mod/svg2mod/files/7732388/example-svg.tar.gz)

**Comment by Albert-IV** [comment]
Oh nice, thank you!
