### ISSUE TITLE
Please include more detailed instructions on installation/use / difficulty installing

### ISSUE THREAD

**Issue by cnlohr** [svg2mod/svg2mod#57]
### The problem

I do the following (Using Win10, tried both WSL and the Python Foundation's system install of Python).

```
pip install svg2mod
```
It works. `Successfully installed fonttools-4.39.0 svg2mod-1.2`

If I try doing this in WSL, I get
```
cnlohr@DESKTOP-S51DART:/mnt/c/temp$ svg2mod
svg2mod: command not found
```

If I try doing this in Windows, I get

```
c:\projects\svg2mod\svg2mod>svg2mod
'svg2mod' is not recognized as an internal or external command,
operable program or batch file.
```

If I try running svg2mod from this repo (same in WSL and Windows), I get:
```
svg2mod>python3 svg2mod
C:\Users\cnlohr\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe: can't find '__main__' module in 'c:\\projects\\svg2mod\\svg2mod'
```

If I try to run the python file directly (in WSL or Windows), I get:
```
svg2mod\svg2mod>python3 svg2mod.py
Traceback (most recent call last):
  File "c:\projects\svg2mod\svg2mod\svg2mod.py", line 25, in <module>
    from svg2mod import svg
  File "c:\projects\svg2mod\svg2mod\svg2mod.py", line 25, in <module>
    from svg2mod import svg
ImportError: cannot import name 'svg' from partially initialized module 'svg2mod' (most likely due to a circular import) (c:\projects\svg2mod\svg2mod\svg2mod.py)
```

I can't run `setup.py` on this system because it doesn't understand installing to a user, it seems.  Or maybe I am running setup.py wrong.  There are no instructions on how to use it.

If I try running setup.py on WSL, I get:
```
cnlohr@DESKTOP-S51DART:/mnt/c/projects/svg2mod$ python3 setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/test-easy-install-1808.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.8/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.
```
Indeed, it does not have write access!

Windows warns me, and then still fails.
```
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-26128.write-test'
```

Can anyone include detailed instructions or a requirement document or something to help folks who just want to use to use these tools.  Also, I urge you to add more details instructions to the readme.

### Version

1.2 and 1.2-3-gd9b5dd0

### Command line

Variety (See above)

### Debug output

```txt
Cannot run tool.
```

### Sample file and additional information

See issue.

**Comment by Sodium-Hydrogen** [comment]
This looks like an issue where python (pip) is not installing it into your execution path.

This [link](https://www.alphr.com/pip-is-not-recognized-as-an-internal-or-external-command/) shows multiple options to fix this.

If you do not want to fix the path issues you need to tell python that this is a module to load like this: `python3 -m svg2mod.cli`

As for the setup.py, it isn't really needed, but the easiest way to get it built is with `pip install .` which will try to install everything defined in the setup.py file.
